// ── The tutorial tour, as data ──
//
// Each chapter is one take: a list of present.* calls played back to back (see
// present.js). Every chapter after the first ends on a chapter card, so the
// pause while whoever is recording starts the next one falls on a still title
// rather than on a frozen screen.
//
// {seebOrder} and the rest are bill numbers minted fresh by newTake at the top
// of the intro, so a retake never collides with an earlier take's orders.
//
// Before the first take: the address carries ?present, nobody is signed in,
// present.pins() holds the codes for SCC, MOUJ, MGM and WH, and the lens shelf
// carries the demo lines the script shops for (SPH -2.50 and SPH -4.00).

const nav = m => ['tap', `a.nav-item[href="#/${m}"]`];
const beat = (ms = 2200) => ['wait', ms];

const intro = [
  ['newTake'],
  ['card', 'FOC Portal', 'One place for every branch, fitting centre, clinic and the warehouse', 'How it works'],
  beat(3400),
  ['card'],
  ['caption', 'Every location signs in from the same page'],
  beat(1800),
  ['focus', '.lp-wh'],
  ['caption', 'The warehouse sits on top…'],
  beat(1800),
  ['focus', '.lp-cols'],
  ['caption', '…with every branch, fitting centre and clinic below it', 'Pick your own location to begin'],
  beat(2600),
  ['reset'],
  ['tap', '[data-loc="SCC"]'],
  ['caption', 'Then enter your location’s six-digit code', 'Each location has its own — the warehouse can change any of them'],
  ['focus', '.pin-card', { zoom: 1.5 }],
  ['typePin', 'SCC'],
  beat(500),
  ['reset'],
  ['tap', '#pin-go'],
  ['caption'],
  ['waitFor', '.shell'],
  beat(1200),
];

const seeb = [
  ['card', 'Seeb City Centre', 'A retail branch sells the frame, sends it out for lenses, and hands it back to the customer', 'Chapter 1 · Retail branch'],
  beat(3000),
  ['card'],

  // ── fitting log ──
  ['caption', 'Fitting Log', 'Every frame that leaves the branch to have its lenses fitted'],
  ['focus', '#f-stats'],
  beat(2000),
  ['caption', 'Active orders, urgent ones, and the ones waiting on you'],
  beat(1800),
  ['focus', '#f-chips'],
  ['caption', 'Filter by where each frame is on its journey'],
  beat(2200),
  ['reset'],
  ['caption', 'A customer has bought glasses — log the frame'],
  ['tap', 'New fitting order'],
  ['focus', '.modal', { zoom: 1.35 }],
  ['caption', 'The bill number from the bill book, and the customer’s name', 'Both are required'],
  ['type', '#nf [name="ref"]', '{seebOrder}'],
  ['type', '#nf [name="customer"]', 'Ahmed Al Balushi'],
  beat(800),
  ['reset'],
  ['tap', '#nf [type="submit"]'],
  ['waitFor', 'text={seebOrder}'],
  ['caption', 'Logged — it reads “Waiting for Lenses” until it leaves the branch'],
  ['focus', '{seebOrder}'],
  beat(2000),
  ['reset'],
  ['caption', 'When the driver collects it: Send to fitter'],
  ['tap', '{seebOrder} >> Send to fitter'],
  ['caption', 'Choose the fitting centre that will cut the lenses'],
  ['focus', '.picker-grid', { zoom: 1.4 }],
  beat(1800),
  ['reset'],
  ['tap', '[data-fitter="MGM"]'],
  beat(900),
  ['caption', 'Now it reads “Waiting to be Fitted”', 'Muscat Grand Mall sees it coming straight away'],
  ['focus', '{seebOrder} >> .row-status', { zoom: 1.8 }],
  beat(2400),
  ['focus', '{seebOrder} >> .row-journey', { zoom: 1.8 }],
  ['caption', 'Its journey: Seeb → Muscat Grand Mall → back to Seeb'],
  beat(2400),
  ['reset'],
  ['caption', 'Open any order to see its whole history'],
  ['tap', '{seebOrder} >> [data-open]'],
  ['focus', '.drawer .timeline'],
  beat(2400),
  ['reset'],
  ['tap', '.drawer [data-close]'],

  // ── stock requests ──
  ['caption', 'Stock Requests', 'Order stock from the warehouse'],
  nav('stock'),
  beat(900),
  ['tap', 'New stock request'],
  ['focus', '.modal', { zoom: 1.2 }],
  ['caption', 'One line per item: category, then brand, who it’s for and how many'],
  ['choose', '[data-f="category"][data-i="0"]', 'Sunglasses'],
  ['choose', '[data-f="brand"][data-i="0"]', 'Ray-Ban'],
  ['choose', '[data-f="audience"][data-i="0"]', 'Women'],
  ['type', '[data-f="qty"][data-i="0"]', '6'],
  ['caption', 'Add as many lines as you need'],
  ['tap', '.modal [data-add]'],
  ['choose', '[data-f="category"][data-i="1"]', 'Cleaning kits'],
  ['type', '[data-f="qty"][data-i="1"]', '4'],
  ['type', '#req-note', 'Weekend promotion'],
  beat(600),
  ['reset'],
  ['tap', '.modal [data-send]'],
  beat(1200),
  ['caption', 'Placed — it lands in the warehouse’s queue at once'],
  ['focus', '#s-list .row'],
  beat(2200),
  ['reset'],

  // ── lens stock ──
  ['caption', 'Lens Stock', 'The loose lenses on the shelf at Muscat Grand Mall'],
  nav('lens'),
  beat(900),
  ['focus', '.toolbar'],
  ['caption', 'Filter by type, index and coating — or search for a power'],
  beat(2200),
  ['focus', 'SPH -2.50 >> .lens-card', { zoom: 1.7 }],
  ['caption', 'Each card shows the power, and how many are on the shelf'],
  beat(2200),
  ['reset'],
  ['tap', 'SPH -2.50 >> [data-add]'],
  ['tap', 'SPH -2.50 >> [data-plus]'],
  ['caption', 'Two — one for each eye'],
  ['focus', '.cart-bar'],
  beat(1500),
  ['reset'],
  ['tap', 'Review & request'],
  ['focus', '.modal', { zoom: 1.2 }],
  ['caption', 'Who it’s for: the customer and the bill number', 'The fitting order opens from this by itself'],
  ['type', '#lens-cust', 'Fatma Al Hinai'],
  ['type', '#lens-note', '{seebLens}'],
  beat(700),
  ['reset'],
  ['tap', '.modal [data-send]'],
  beat(1400),
  ['caption', 'Sent to Muscat Grand Mall', 'A shop has no bench, so the frame goes over to be cut there'],
  beat(2400),
  ['tap', '.drawer [data-close]'],
  nav('fitting'),
  beat(900),
  ['caption', '…and that job is already in the fitting log', 'Tagged Stock Lens — open it to see which lenses'],
  ['focus', '{seebLens}'],
  beat(2200),
  ['reset'],

  // ── insurance claims ──
  ['caption', 'Insurance Claims', 'A printable receipt for the customer’s insurer'],
  nav('claims'),
  beat(900),
  ['tap', 'New claim receipt'],
  ['type', '#f-bill', '{seebClaim}'],
  ['type', '#f-cust', 'Salim Al Rawahi'],
  ['caption', 'What they bought, and the price in rials'],
  ['type', '[data-it="name"][data-i="0"]', 'Ray-Ban RB5154 frame'],
  ['type', '[data-it="price"][data-i="0"]', '45.000'],
  ['tap', '.modal [data-add]'],
  ['type', '[data-it="name"][data-i="1"]', 'Single vision lenses 1.60 AR'],
  ['type', '[data-it="price"][data-i="1"]', '30.750'],
  ['focus', '.total-chip', { zoom: 1.8 }],
  ['caption', 'The total adds itself up'],
  beat(1600),
  ['caption', 'The prescription — distance and near, for each eye'],
  ['focus', 'table.rx-edit', { zoom: 1.45 }],
  ['type', '[data-rx="d.od.sph"]', '-2.25'],
  ['type', '[data-rx="d.od.cyl"]', '-0.50'],
  ['type', '[data-rx="d.od.axis"]', '180'],
  ['type', '[data-rx="d.od.va"]', '6/6'],
  ['type', '[data-rx="d.os.sph"]', '-2.00'],
  ['type', '[data-rx="d.os.cyl"]', '-0.75'],
  ['type', '[data-rx="d.os.axis"]', '175'],
  ['type', '[data-rx="d.os.va"]', '6/6'],
  ['type', '[data-rx="add.od"]', '+1.00'],
  ['type', '[data-rx="add.os"]', '+1.00'],
  beat(1000),
  ['reset'],
  ['choose', '#f-pay', 'Card'],
  ['tap', '.modal [data-save]'],
  beat(1500),
  ['caption', 'Ready to print and sign', 'Clinics raise their claims exactly the same way'],
  beat(3000),
  ['tap', '.modal [data-close]'],
  ['caption'],
  ['card', 'Next: Al Mouj', 'A fitting centre that cuts lenses on its own bench', 'Chapter 2'],
];

const mouj = [
  ['as', 'MOUJ', { title: 'Al Mouj', sub: 'A fitting centre — it cuts lenses on its own bench', kicker: 'Chapter 2 · Fitting centre' }],
  ['caption', 'Al Mouj needs a pair of lenses from Muscat Grand Mall’s shelf'],
  nav('lens'),
  beat(900),
  ['tap', 'SPH -4.00 >> [data-add]'],
  ['tap', 'SPH -4.00 >> [data-plus]'],
  ['tap', 'Review & request'],
  ['focus', '.modal', { zoom: 1.2 }],
  ['caption', 'A fitting centre chooses how the job gets done'],
  ['focus', '.fulfil', { zoom: 1.6 }],
  ['caption', 'Send the frame over to be cut there…', '…or have the lenses sent here and cut them yourself'],
  beat(3200),
  ['tap', 'Receive the lenses'],
  beat(600),
  ['reset'],
  ['type', '#lens-cust', 'Maryam Al Kindi'],
  ['type', '#lens-note', '{moujLens}'],
  ['tap', '.modal [data-send]'],
  beat(1400),
  ['focus', '.drawer .fulfil-chip', { zoom: 1.8 }],
  ['caption', 'Marked “Lenses come here”'],
  beat(2000),
  ['reset'],
  ['tap', '.drawer [data-close]'],
  nav('fitting'),
  beat(900),
  ['caption', 'The job is already in Al Mouj’s fitting log', 'In-house — the frame never leaves the building'],
  ['focus', '{moujLens}'],
  beat(2400),
  ['reset'],
  ['tap', '{moujLens} >> [data-open]'],
  ['focus', '.drawer .journey'],
  ['caption', 'It reads “Waiting for Lenses” until they arrive'],
  beat(2200),
  ['focus', '.drawer .timeline'],
  beat(1800),
  ['reset'],
  ['tap', '.drawer [data-close]'],
  ['caption'],
  ['card', 'Next: Muscat Grand Mall', 'A fitting centre — and the keeper of the lens shelf', 'Chapter 3'],
];

const mgm = [
  ['as', 'MGM', { title: 'Muscat Grand Mall', sub: 'Fits lenses for other branches and for itself — and keeps the lens shelf', kicker: 'Chapter 3 · Fitting centre & lens holder' }],

  // ── a frame from another branch ──
  ['caption', 'Seeb’s frame is on its way here'],
  ['focus', '{seebOrder}'],
  beat(2000),
  ['reset'],
  ['caption', 'Confirm arrival when the driver drops it off'],
  ['tap', '{seebOrder} >> Confirm arrival'],
  beat(900),
  ['caption', 'Mark ready once the lenses are fitted'],
  ['tap', '{seebOrder} >> Mark ready'],
  beat(900),
  ['caption', 'Send it back with the driver'],
  ['tap', '{seebOrder} >> Send to branch'],
  beat(900),
  ['focus', '{seebOrder} >> .row-status', { zoom: 1.8 }],
  ['caption', '“Returning to SCC” — Seeb knows it’s on its way back'],
  beat(2400),
  ['reset'],

  // ── a job it keeps ──
  ['caption', 'A customer buys glasses here, at Muscat Grand Mall'],
  ['tap', 'New fitting order'],
  ['type', '#nf [name="ref"]', '{mgmOrder}'],
  ['type', '#nf [name="customer"]', 'Khalid Al Harthy'],
  ['focus', '.modal p.muted', { zoom: 1.6 }],
  ['caption', 'It reads “Waiting for Lenses” until they come in from the supplier'],
  beat(2400),
  ['reset'],
  ['tap', '#nf [type="submit"]'],
  ['waitFor', 'text={mgmOrder}'],
  beat(600),
  ['caption', 'Lenses in? Send to fitter — and keep it here'],
  ['tap', '{mgmOrder} >> Send to fitter'],
  ['focus', '.picker-home', { zoom: 1.6 }],
  ['caption', 'Your own centre comes first: no transit, no driver'],
  beat(2400),
  ['reset'],
  ['tap', '.picker-home'],
  beat(900),
  ['focus', '{mgmOrder}'],
  ['caption', 'Straight to “In fitting”'],
  beat(1800),
  ['reset'],
  ['tap', '{mgmOrder} >> Mark as done'],
  beat(900),
  ['tap', '[data-chip="delivered"]'],
  ['focus', '{mgmOrder}'],
  ['caption', 'Done — it waits here for the customer to collect it', 'No transit and no delivery step'],
  beat(2400),
  ['reset'],
  ['tap', '[data-chip="active"]'],

  // ── lens requests ──
  ['caption', 'Lens Stock — every branch’s lens requests arrive here'],
  nav('lens'),
  beat(900),
  ['focus', '#l-body'],
  beat(1800),
  ['reset'],
  ['tap', 'Al Mouj'],
  ['focus', '.drawer .fulfil-chip', { zoom: 1.8 }],
  ['caption', 'Al Mouj will cut these itself, so the lenses travel'],
  beat(2400),
  ['reset'],
  ['focus', '.drawer .timeline'],
  ['caption', 'Nothing to confirm', 'The lenses came off the shelf the moment Al Mouj asked'],
  beat(2400),
  ['reset'],
  ['tap', '.drawer [data-close]'],
  ['tap', 'Seeb City Centre'],
  ['focus', '.drawer .fulfil-chip', { zoom: 1.8 }],
  ['caption', 'Seeb’s frame is coming here, so these stay on this bench'],
  beat(2200),
  ['reset'],
  ['tap', '.drawer [data-close]'],

  // ── the shelf ──
  ['tap', 'My shelf'],
  ['caption', 'The shelf — counts are edited right here'],
  ['focus', '.stock-table'],
  beat(2200),
  ['reset'],
  ['caption', 'Hide empty keeps sold-out lines out of the way'],
  ['tap', 'Hide empty'],
  beat(1300),
  ['tap', 'Hide empty'],
  beat(700),
  ['caption', 'The cog decides what the shelf can hold'],
  ['focus', '#l-cog', { zoom: 2 }],
  beat(1500),
  ['reset'],
  ['tap', '#l-cog'],
  ['focus', '.modal', { zoom: 1.2 }],
  ['caption', 'Add a new index…'],
  ['type', '[data-add="indices"] input', '1.80'],
  ['tap', '[data-add="indices"] [type="submit"]'],
  beat(900),
  ['caption', '…or a new coating', 'Every branch’s filters pick it up at once'],
  ['type', '[data-add="coatings"] input', 'Anti-fog'],
  ['tap', '[data-add="coatings"] [type="submit"]'],
  beat(900),
  ['caption', 'Anything not on the shelf can be taken off again'],
  ['tap', '1.80 >> [data-del]'],
  beat(700),
  ['tap', 'Anti-fog >> [data-del]'],
  beat(700),
  ['reset'],
  ['tap', '.modal [data-close]'],
  ['caption', 'Add lens stock tops up a line, or starts a new one'],
  ['tap', 'Add lens stock'],
  ['focus', '.modal', { zoom: 1.25 }],
  beat(2600),
  ['reset'],
  ['tap', '.modal [data-close]'],
  ['caption'],
  ['card', 'Back at Al Mouj', 'The lenses have arrived from Muscat Grand Mall', 'Chapter 4'],
];

const moujDone = [
  ['as', 'MOUJ', { title: 'Back at Al Mouj', sub: 'The lenses have arrived from Muscat Grand Mall', kicker: 'Chapter 4 · Fitting centre' }],
  ['focus', '{moujLens}'],
  ['caption', 'The lenses are in — start fitting'],
  beat(1800),
  ['reset'],
  ['tap', '{moujLens} >> Start fitting'],
  beat(900),
  ['focus', '{moujLens} >> .row-status', { zoom: 1.8 }],
  ['caption', 'In fitting'],
  beat(1600),
  ['reset'],
  ['tap', '{moujLens} >> Mark as done'],
  beat(900),
  ['tap', '[data-chip="delivered"]'],
  ['focus', '{moujLens}'],
  ['caption', 'Done — ready for Maryam to collect'],
  beat(2400),
  ['reset'],
  ['tap', '[data-chip="active"]'],
  ['caption'],
  ['card', 'Next: the Warehouse', 'Sees every branch, fulfils stock requests and runs the settings', 'Chapter 5'],
];

const warehouse = [
  ['as', 'WH', { title: 'The Warehouse', sub: 'Sees every branch, fulfils stock requests and runs the settings', kicker: 'Chapter 5 · Warehouse' }],
  ['caption', 'The warehouse sees every frame across the network'],
  ['focus', '#f-list'],
  beat(2200),
  ['focus', '#f-origin', { zoom: 1.8 }],
  ['caption', 'Narrow it to one branch, or to one fitting centre'],
  beat(2000),
  ['reset'],

  ['caption', 'The request queue — Seeb’s request is waiting'],
  nav('stock'),
  beat(900),
  ['tap', 'Seeb City Centre'],
  ['focus', '.drawer', { zoom: 1.1 }],
  beat(2200),
  ['reset'],
  ['caption', 'Mark completed when it ships — Seeb sees it straight away'],
  ['tap', '.drawer [data-complete]'],
  beat(1400),
  ['tap', '.drawer [data-close]'],

  ['caption', 'Every branch’s and clinic’s claim receipts, in one list'],
  nav('claims'),
  beat(900),
  ['focus', '#c-list'],
  beat(2200),
  ['reset'],

  ['caption', 'Settings — what branches can request'],
  nav('settings'),
  beat(900),
  ['focus', '#set-cats'],
  beat(2400),
  ['focus', '#set-groups'],
  ['caption', 'Brand groups — which brands each category offers'],
  beat(2200),
  ['reset'],
  ['type', '[data-add-brand="All brands"] input', 'Demo Optics'],
  ['tap', '[data-add-brand="All brands"] [type="submit"]'],
  beat(900),
  ['caption', 'Every branch’s request form offers it at once'],
  ['focus', 'Demo Optics', { zoom: 1.8 }],
  beat(1800),
  ['reset'],
  ['tap', 'Demo Optics >> [data-del-brand]'],
  beat(700),
  ['focus', '#set-access'],
  ['caption', 'Branch access — set or change any location’s code', 'Codes are never shown, only replaced'],
  beat(2800),
  ['reset'],
  ['caption'],
  ['card', 'Back at Seeb City Centre', 'The frame comes home', 'Finale'],
];

const finale = [
  ['as', 'SCC', { title: 'Back at Seeb City Centre', sub: 'The frame comes home', kicker: 'Finale' }],
  ['focus', '{seebOrder}'],
  ['caption', '“Returning to SCC” — and the driver is here'],
  beat(2200),
  ['reset'],
  ['tap', '{seebOrder} >> Confirm delivery'],
  beat(900),
  ['tap', '[data-chip="delivered"]'],
  ['focus', '{seebOrder}'],
  ['caption', 'Delivered — the whole round trip, start to finish'],
  beat(2600),
  ['reset'],
  ['tap', '[data-chip="active"]'],
  ['caption'],
  ['card', 'That’s FOC Portal', 'Every branch, every frame, every lens — in one place', 'foc-portal.org'],
  beat(4000),
];

export const TOUR = { intro, seeb, mouj, mgm, moujDone, warehouse, finale };
export const CHAPTERS = Object.keys(TOUR);
